src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\DateTime;
use Cocur\Slugify\Slugify;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $nbSeats = null;

    #[ORM\Column(nullable: true)]
    private ?int $nbDoors = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?float $cost = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $isSold = false;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $color = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'cars')]
    private Collection $categories;

    public function __construct() {
        $this->created_at = new \DateTime();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbSeats(): ?int
    {
        return $this->nbSeats;
    }

    public function setNbSeats(?int $nbSeats): static
    {
        $this->nbSeats = $nbSeats;

        return $this;
    }

    public function getNbDoors(): ?int
    {
        return $this->nbDoors;
    }

    public function setNbDoors(?int $nbDoors): static
    {
        $this->nbDoors = $nbDoors;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCost(): ?float
    {
        return $this->cost;
    }

    public function setCost(float $cost): static
    {
        $this->cost = $cost;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isIsSold(): ?bool
    {
        return $this->isSold;
    }

    public function setIsSold(bool $isSold): static
    {
        $this->isSold = $isSold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getFormattedCost() : string {
        return number_format($this->cost,0,'',' ');
    }

    public function getSlug() : string {
        return (new Slugify())->slugify($this->name);
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): static
    {
        $this->color = $color;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->addCar($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        if ($this->categories->removeElement($category)) {
            $category->removeCar($this);
        }

        return $this;
    }

    public function getEngine(): ?Engine
    {
        return $this->engine;
    }

    public function setEngine(?Engine $engine): static
    {
        $this->engine = $engine;

        return $this;
    }
}

src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\Car;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('nbSeats', null , [
                'label' => 'Seats'
            ])
            ->add('nbDoors', null, [
                'label' => 'Doors'
            ])
            ->add('cost')
            ->add('color')
            ->add('description')
            ->add('categories', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'multiple' => 'false'
                
                ])
            ->add('isSold', null, [
                'label' =>'Sold?'
            ]
            )
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}

src/Controller/CarController.php
<?php

namespace Controller;

use App\Entity\Car;
use Entity\SearchCriteria;
use App\Form\SearchCriteriaType;
use App\Repository\CarRepository; 
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CarController extends AbstractController
{
    private $twig;

    private $repo;

    private $em;

    public function __construct($twig, CarRepository $repo, EntityManagerInterface $em) {
        $this->twig = $twig;
        $this->repo = $repo;
        $this->em = $em;
    }  

    public function index(PaginatorInterface $paginator, Request $request) : Response 
    {

        // chercher les voitures de la base de données
        $search = new SearchCriteria();

        // création du formulaire de recherche et le stocker dans la variable $form
        $form = $this->createForm(SearchCriteriaType::class, $search);
        $form->handleRequest($request);

        // pagination des voitures
        $cars = $paginator->paginate(
            $this->repo->findAllNotSold($search),
            $request->query->getInt('page', 1),
            20
        );

        // retourne la liste des voitures paginée
        return $this->render('car/index.html.twig', [
            'current_menu' => 'cars',
            'availableCars' => $cars,
            'form' => $form->createView()
        ]
        );
    }

    public function show($slug, $id) : Response
    {
        $car = $this->repo->find($id);

        $carSlug = $car->getSlug();
        
        if($carSlug !== $slug) {
            return $this->redirectToRoute('car', [
                'id' => $car->getId(),
                'slug' => $carSlug
            ], 301); 
        }

        return $this->render('car/show.html.twig' , [
            'car' => $car,
            'current_menu' => 'cars'
        ]);
    }

}

templates/car/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Check our cars catalogue' %}

{% block body %} 

    <div class="jumbotron">
        <div class="container">


            {{form_start(form)}}
        <button class="btn btn-primary">Search</button>
            {{form_end(form)}}
        </div>
    </div>  

    <div class="container mt-4">
        <h1>Check our cars catalogue</h1>
    </div>
    <div class="container">
        <div class="row flex">
        <!-- Affichier les détails de chaque voiture en utilisant la boucle for -->
         <!--   { for car in availableCars }  => Pour chaque voiture dans la liste des voitures disponible, fais le code HTML ci-dessous -->
            {% for car in availableCars %}
            <div class="col-3" >
                <div class="card" >
                        <div class="card-body" >
                            <h5 class="card-title" >
                                <a href="{{ path('car', {id: car.id, slug: car.slug}) }}">{{ car.name }} - {{ car.color }} </a>
                            </h5>
                            <div class = "text-primary" > 
                                {{ car.formattedCost }} €
                            </div>
                            <div class="row flex" >
                                <div class="col-6">Doors: {{ car.nbDoors }}</div>
                                <div class="col-6">Seats: {{ car.nbSeats }}</div>
                            </div>
                        </div>      
                    </div>
            </div>
            {% endfor %}
        
        </div>
        <div class="paginator">
            {{ knp_pagination_render(availableCars)}}
        </div>
    </div>
{% endblock %} 

templates/car/show.html.twig
{% extends 'base.html.twig' %}

{% block title car.name %}


{% block body %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4">
                <h1>{{ car.name }} - {{ car.color }}</h1>
                <h2>{{ car.nbSeats }} seats - {{ car.nbDoors }} doors</h2>
                <div class="text-primary" style="font-size: 4rem;font-weight:bold;">
                    {{ car.formattedCost }} €
                </div>
            </div>
        </div>

        <p>{{ car.description | nl2br }} </p>

        <div class="row">
            <div class="col-md-8">
                <table class="table table-striped">
                    <tr>
                        <td>Color</td>
                        <td>{{car.color}}</td>
                    </tr>
                    <tr>
                        <td>Number of doors</td>
                        <td>{{ car.nbDoors }}</td>
                    </tr>
                    <tr>
                        <td>Number of seats</td>
                        <td>{{ car.nbSeats }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}